<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>EasyDeliveryCoSteeringWheel</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>A:\SteamLibrary\steamapps\common\Easy Delivery Co\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>A:\SteamLibrary\steamapps\common\Easy Delivery Co\EasyDeliveryCo_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>A:\SteamLibrary\steamapps\common\Easy Delivery Co\EasyDeliveryCo_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>A:\SteamLibrary\steamapps\common\Easy Delivery Co\EasyDeliveryCo_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>A:\SteamLibrary\steamapps\common\Easy Delivery Co\EasyDeliveryCo_Data\Managed\UnityEngine.InputModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>A:\SteamLibrary\steamapps\common\Easy Delivery Co\EasyDeliveryCo_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>A:\SteamLibrary\steamapps\common\Easy Delivery Co\EasyDeliveryCo_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>A:\SteamLibrary\steamapps\common\Easy Delivery Co\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>A:\SteamLibrary\steamapps\common\Easy Delivery Co\EasyDeliveryCo_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
